[flavor]
dark = "true"
name = "iterm2-dark"

[manager]
cwd = { fg = "#BFBAB0" }
hovered = { fg = "#0F1419", bg = "#F29718" }
preview_hovered = { fg = "#F29718" }
find_keyword = { fg = "#0F1419", bg = "#F29718" }
marker_selected = { fg = "#C2D94C", bg = "#16242E" }
marker_copied   = { fg = "#59C2FF", bg = "#16242E" }
marker_cut      = { fg = "#FF7733", bg = "#16242E" }

[status]
normal = { fg = "#BFBAB0", bg = "#0F1419" }
insert = { fg = "#0F1419", bg = "#59C2FF" }
select = { fg = "#0F1419", bg = "#F29718" }

[completion]
active   = { fg = "#0F1419", bg = "#F29718" }
inactive = { fg = "#BFBAB0", bg = "#131E27" }

[input]
title = { fg = "#59C2FF" }
border = { fg = "#20272C" }
selected = { fg = "#0F1419", bg = "#F29718" }

[progress]
normal = { fg = "#C2D94C", bg = "#0A0E12" }
error  = { fg = "#FF3333", bg = "#0A0E12" }

[which]
mask  = { bg = "#0F1419" }
cand  = { fg = "#59C2FF" }
rest  = { fg = "#BFBAB0" }
desc  = { fg = "#95E6CB" }
separator = "#5C6773"

[help]
on  = { fg = "#F29718" }
off = { fg = "#5C6773" }

[log]
error = { fg = "#FF3333" }
warn  = { fg = "#FF7733" }
info  = { fg = "#59C2FF" }
debug = { fg = "#5C6773" }


[icon]
prepend_conds = [
	{ if = "hidden & dir",  text = " " },  # Hidden directories
	{ if = "dir",           text = " " },  # Directories
	{ if = "!(dir | link)", text = " " },  # Normal files (not directories or symlinks)
]

prepend_dirs = [
        { name = "durdraw", text = "󰏘 " }, # Example: custom icon for "Durdraw"
        { name = "Applications", text = "󱌢 " }, # Example: custom icon for "applications"
        { name = "Library", text = " " }, # Example: custom icon for "Library"
        { name = "projects", text = " " }, # Example: custom icon for "projects"
        { name = "res", text = " " }, # Example: custom icon for "resources"
        { name = "ghostty", text = " " }, # Example: custom icon for "resources"
        { name = "yazi", text = "󰇥 " }, # Example: custom icon for "resources"
        { name = "btop", text = "󰍛 " }, # Example: custom icon for "resources"
        { name = "neofetch", text = "󰨇 " }, # Example: custom icon for "resources"
        { name = "fastfetch", text = "󰨇 " }, # Example: custom icon for "resources"
        { name = "linearmouse", text = " " }, # Example: custom icon for "resources"
        { name = "raycast", text = " " }, # Example: custom icon for "resources"
        { name = "zsh", text = "󱙷 " }, # Example: custom icon for "resources"
        { name = "micro", text = "󱩼 " }, # Example: custom icon for "resources"
        { name = "Shared", text = " " }, # Example: custom icon for "resources"
        { name = "sai", text = " " }, # Example: custom icon for "resources"
        { name = "admin", text = " " }, # Example: custom icon for "resources"
	# For hidded folders
	{ name = ".durdraw", text = "󰽉 " },
	{ name = ".cache", text = " " },
	{ name = ".local", text = " " },
	{ name = ".thumbnails", text = " " },
	{ name = ".Trash", text = " " }, 
	{ name = ".zsh_sessions", text = "󱙷 " }, 
	{ name = ".vim", text = " " },
	{ name = ".vscode", text = " " },
	{ name = ".vscode-oss", text = " " },
]
append_exts = [
	# ...
]



